#!/bin/sh
#
#  Try to figure out into which directory the
#  tar archive containing the source code should
#  be installed.


echo -ne macrofiles:\\t > "$1"
echo -n $(rpmbuild --showrc | awk "/^macrofiles[^a-zA-Z_]/{print \$3}") >> "$1"
echo ":`pwd`/rpmmacros" >> "$1"

